package com.revature.models;

public class Role {

    private int role_id;
    private String role_title;

    //no args
    public Role() {
    }

    //all args
    public Role(int role_id, String role_title) {
        this.role_id = role_id;
        this.role_title = role_title;
    }

    //all args minus id constructor. For when we need a serial id to get generated
    //we don't have to worry about it! It will get generated by the database
    public Role(String role_title) {
        this.role_title = role_title;
    }

    public int getRole_id() {
        return role_id;
    }
    public void setRole_id(int role_id) {
        this.role_id = role_id;
    }

    public String getRole_title() {
        return role_title;
    }
    public void setRole_title(String role_title) {
        this.role_title = role_title;
    }

    @Override
    public String toString() {
        return "Role{" +
                "role_id=" + role_id +
                ", role_title='" + role_title + '}';
    }
}